{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from selenium import webdriver\n",
    "from bs4 import BeautifulSoup\n",
    "from time import sleep\n",
    "import pandas as pd\n",
    "\n",
    "df = pd.DataFrame()\n",
    "category = 'enterprises'\n",
    "\n",
    "\n",
    "site_list = ['http://designspiration.net/image/31711833267/',\n",
    "             'http://tatobutori.prosite.com/182824/6788722/work/honda-motorcycles-maze',\n",
    "             'https://www.behance.net/gallery/20914789/Ford-Rear-View-Camera-Print-Ads',\n",
    "             'https://www.behance.net/gallery/10641505/Alzheimers-Disease-International',\n",
    "             'http://adsoftheworld.com/media/print/belgian_league_of_alhzeimer_alhzeimers_day',\n",
    "             'https://www.behance.net/gallery/509295/CARULLA-Knives',\n",
    "             'http://theinspirationgrid.com/better-by-bike-posters-by-la-comunidad/',\n",
    "             'https://www.behance.net/gallery/10183083/Nutella-Ad-Campaign',\n",
    "             'http://designtaxi.com/news/367481/Clever-Sharpie-Print-Ads-Show-How-Great-Logos-Were-Started/',\n",
    "             'https://www.behance.net/gallery/8263139/Aspirina-Bayer',\n",
    "             'https://www.behance.net/gallery/PARISLOFT-ADVERTISING/1748942',\n",
    "             'http://thisisnthappiness.com/post/36674956083/i-believe-in-advertising',\n",
    "             'https://www.behance.net/gallery/28426457/Faber-Castell-Idea-Print-Campaign',\n",
    "             'https://www.behance.net/gallery/Softies/8296169',\n",
    "             'http://www.bitrebels.com/design/retro-game-posters-highlight-environmental-issues/',\n",
    "             'https://www.canva.com/signup?signupRedirect=%2Fdesign%3Fcreate%3Dtrue%26media%3DMACNwt8s9f0&loginRedirect=%2Fdesign%3Fcreate%3Dtrue%26media%3DMACNwt8s9f0',\n",
    "             'https://www.behance.net/gallery/18726717/PRINT-Pins-El-Universo',\n",
    "             'http://www.hvilshoj.com/146176/5755745/portfolio/eva-solo-instagram-02',\n",
    "             'http://www.gqmagazine.fr/culture-web/le-topito-de-la-semaine/diaporama/les-plus-belles-publicits-minimalistes/2045#7',\n",
    "             'https://www.behance.net/gallery/7283785/Distronic-Plus-Mercedes-Benz',\n",
    "             'https://www.behance.net/gallery/28144801/Cut-A-Tree-Kill-A-Life',\n",
    "             'https://www.behance.net/gallery/25707573/FOXY-Asso-Ultra-Glass',\n",
    "             'https://www.behance.net/gallery/16197577/MARSHALL-HEADPHONES-CANNES-YOUNG-LIONS-UKRAINE',\n",
    "             'http://www.inspiration-now.com/miyabi-ads-by-herezie-paris/',\n",
    "             'http://www.inspiration-now.com/inglorious-fruits-vegetables-by-marcel-paris/',\n",
    "             'http://designbeep.com/2011/10/29/25-fresh-examples-of-effective-ad-campaigns/',\n",
    "             'https://www.behance.net/gallery/4139709/Pringles-Galaxy',\n",
    "             'http://www.luerzersarchive.com/en/features/campaigns/your-favourite-print-ads-of-2014-739.html',\n",
    "             'https://www.behance.net/gallery/10065759/Strawberry-Fanta',\n",
    "             'http://adsoftheworld.com/media/print/raid_bug_killer_bumblebee',\n",
    "             'http://www.mylittlerecettes.com/de-jolis-thes-aromatises/',\n",
    "             'http://www.adweek.com/adfreak/ikeas-family-tree-ads-show-beds-which-each-new-generation-was-conceived-157659',\n",
    "             'http://www.luerzersarchive.com/en/magazine/print-detail/mccann-healthcare-worldwide-japan-inc-46499.html',\n",
    "             'http://www.kickvick.com/genius-double-page-magazine-ads/',\n",
    "             'http://www.kickvick.com/genius-double-page-magazine-ads/',\n",
    "             'http://www.fromupnorth.com/creative-advertising-1228/',\n",
    "             'http://www.unp.me/f44/extremely-clever-ads-80425/index2.html',\n",
    "             'http://www.arnoldfurnace.com/creative/work/bees',\n",
    "             'https://daviddoctorrose.wordpress.com/2008/02/16/an-extra-large-coffee-from-mcdonalds/',\n",
    "             'http://www.cuded.com/2012/01/plant-for-the-planet-traffic/',\n",
    "             'http://www.fromupnorth.com/creative-advertising-673/',\n",
    "             'http://www.creativebloq.com/inspiration/print-ads-1233780',\n",
    "             'https://www.behance.net/gallery/University-Cruzeiro-do-Sul-Visagism/9760617',\n",
    "             'http://www.creativebloq.com/inspiration/print-ads-1233780',\n",
    "             'http://guff.com/some-of-the-most-clever-advertisements-by-popular-brands/cd-usb-drive',\n",
    "             'http://www.creativebloq.com/inspiration/print-ads-1233780',\n",
    "             'https://www.behance.net/gallery/10891255/TazoExplore-the-World',\n",
    "             'http://www.coloribus.com/adsarchive/prints/volkswagen-car-parts-a-bad-affects-the-entire-system-2-14400005/',\n",
    "             'https://www.jwt.com/en/dubai',\n",
    "             'https://www.behance.net/ethosmtl',\n",
    "             'https://joepublicunited.co.za/',\n",
    "             'http://www.lamanostudio.com/',\n",
    "             'http://www.bartleboglehegarty.com/london/',\n",
    "             'http://www.davidtheagency.com/',\n",
    "             ''\n",
    "    \n",
    "             ]\n",
    "\n",
    "\n",
    "\n",
    "driver = webdriver.Chrome(executable_path='/home/acer1/chromedriver')\n",
    "for site in site_list:\n",
    "    driver.get(site)\n",
    "    sleep(5)\n",
    "    hypertext = driver.find_element_by_tag_name(\"body\").get_attribute('innerHTML')\n",
    "    text = driver.find_element_by_tag_name(\"body\").get_attribute('innerText')\n",
    "    df = df.append({'hypertext':hypertext,'text':text,'website':site,'category':category},ignore_index=True)\n",
    "filename = '/home/acer1/sitedata_enterprises.xls'\n",
    "writer = pd.ExcelWriter(filename, engine='xlsxwriter')\n",
    "df.to_excel(writer)\n",
    "writer.save()\n",
    "driver.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
